- hosts: all
  become: true
  vars:
    packages:
      download_url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
      package_name: node_exporter-1.7.0.linux-amd64.tar.gz
    temp_dir: /tmp

  tasks:
    - name: Download Node Exporter
      get_url: 
        url: "{{ packages.download_url }}"
        dest: "{{ temp_dir }}"

    - name: Extract Node Exporter
      unarchive: 
        src: "{{ temp_dir }}/{{ packages.package_name }}"
        dest: "{{ temp_dir }}"
        remote_src: yes
    
    - name: Create prometheus group
      group: 
        name: prometheus
        state: present

    - name: Create prometheus user
      user:
        name: prometheus
        group: prometheus
        shell: /sbin/nologin
        system: yes
        create_home: no

    - name: Copy Node Exporter Binary Files
      copy: 
        src: "{{ temp_dir }}/node_exporter-1.7.0.linux-amd64/node_exporter"
        dest: /usr/local/bin
        owner: root
        mode: "0755"
        group: root
        remote_src: yes

    - name: Creating Node Expoter Service Daemon
      copy:
        dest: "/etc/systemd/system/node-exporter.service"
        content: |
          [Unit]
          Description=Prometheus exporter for machine metrics

          [Service]
          Restart=always
          User=prometheus
          ExecStart=/usr/local/bin/node_exporter
          ExecReload=/bin/kill -HUP $MAINPID
          TimeoutStopSec=20s
          SendSIGKILL=no

          [Install]
          WantedBy=multi-user.target

    - name: Daemon Reload
      systemd: 
        name: node-exporter
        state: reloaded

    - name: Start Node Exporter Service
      systemd: 
        name: node-exporter.service
        state: started
        enabled: yes

    # - name: Clean Temporary Directory
    #   file: 
    #     path: "{{ item }}"